### ISSUE TITLE
Error while running the script (`require': cannot load such file)

### ISSUE THREAD

**Issue by alex-swiftify** [lurado/BetterAppleDocsets#5]
Hi,

Installed ruby and sqlite3 as per instructions.
Trying this script and getting the following.
```
MacBook-Pro-Alex-2:AppleDocs alex$ ruby bad.rb --language=objc --platform=ios --output=.                                                                         
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (
LoadError)                                                                                                                                                       
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                       
        from bad.rb:7:in `<main>' 
```

Any hints to get this working?

**Comment by sebastianludwig** [comment]
Hi Alex, thanks for getting in touch! This is a leftover and not needed anymore. I'll push a version with the `require 'bundler'` line removed in a minute

**Comment by alex-swiftify** [comment]
Thanks, Sebastian - appreciate your super fast reply!

**Comment by alex-swiftify** [comment]
P.S. The script runs successfully with this line removed :)

**Comment by sebastianludwig** [comment]
Nah, thanks to you for reporting the issue 👍 I just pushed the update

I'm also running your command to see if the rest still works...
